[package]
name = "tinyavif"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.19", features = ["derive", "extern_crate_alloc"] }
byteorder = "1"
clap = { version = "4.5.20", features = ["derive"] }
